### ISSUE TITLE
Portal Übergang zur Menu Activity

### ISSUE THREAD

**Issue by SaW2017** [leinad02/SE2_MonstersAndPortals#2]
Im Branch Portal habe ich eine einfache Menu Activity mit Button erstellt um das Portal zu testen. Leider komme ich von dem Portal nicht wieder zurück in die Menu Activity, obwohl ich es mit einem timer (Thread) probiert habe und zudem mit einem einfachen Button. Beides schlägt fehl! Trotz gemeinsamer Suche ist der Fehler noch nicht gefunden.

**Comment by mkloss94** [comment]
Ich hätte da 2 Tipps:

1. Entweder du machst vom MenuActivity zum Portal ein neuen Intent:

`Intent intent = new Intent(this, Portal.class);
                    startActivity(intent);`

2. Oder du kreierst einen neuen Dialog:
`Dialog dialog = new Dialog(this, android.R.style.Theme_Transcluent_NoTitleBar_Fullscreen);` 

und anschließend kannst du diesen Dialog ein XML File zuweisen mit:

`dialog.setContentView(R.layout.portal);`

und zum Schluss brauchst du nur mehr den Dialog anzeigen lassen:

`dialog.show();`

Der Vorteil der 2. Methode wäre, dass du nicht die Aktivitäten wechseln müsstest ;)
